import { localized } from './language';
export const labels = localized({
  settings: 'اللغة والصوت', language: 'بأشمن لغة نهضرو؟', voice: 'اختار الصوت', auto: 'الصوت اللي مناسب', test: 'جرّب الصوت', humor: 'النكت والضحك', on: 'شاعل', off: 'طافي', save: 'سجّل', saveFailed: 'ما تسجلاتش الإعدادات. عاود جرّب.',
  change: 'بدّل الطريق', refresh: 'عاود حسب ليا الطريق', alternative: 'قلّب على طريق آخر', policy: 'واش ندوزو من البيّاج؟', avoid: 'بلا بيّاج', allow: 'البيّاج مسموح', prefer: 'حسب نوع الطريق', apply: 'حسب وبدّل', noAlternative: 'ما لقيناش طريق آخر بهاد الشروط. باقين على الطريق ديالك.', changed: 'ها الطريق الجديدة، يالله بشوية!', noRoute: 'ما لقيناش طريق بهاد الشروط. ما بدّلنا والو.',
  allowNote: 'السماح بالبيّاج ما كيعنيش ضروري ندوزو منّو. الثمن ما معروفش.', demoPin: 'تقدر تسجّل هاد البلاصة. حساب الطريق الحقيقي خاصّو تفعيل الخدمة.', wazeLive: 'معطيات Waze مربوطة', wazeOff: 'معطيات Waze ما مربوطاش', wazeStale: 'معطيات Waze ما تحدّثوش',
}, {
  settings: 'Langue et voix', language: 'Langue', voice: 'Choisir la voix', auto: 'Voix automatique', test: 'Écouter un essai', humor: 'Humour', on: 'Activé', off: 'Désactivé', save: 'Enregistrer', saveFailed: 'Réglages non enregistrés. Réessayez.',
  change: 'Changer de trajet', refresh: 'Recalculer le trajet', alternative: 'Chercher un autre trajet', policy: 'Péages', avoid: 'Sans péage', allow: 'Péages autorisés', prefer: 'Selon le type de trajet', apply: 'Calculer et changer', noAlternative: 'Aucun autre trajet trouvé avec ces critères. Trajet actuel conservé.', changed: 'Nouveau trajet prêt.', noRoute: 'Aucun trajet avec ces critères. Aucun changement.',
  allowNote: 'Autoriser les péages ne force pas leur utilisation. Prix inconnu.', demoPin: 'Ce lieu peut être enregistré. Activez les services pour calculer un trajet réel.', wazeLive: 'Flux Waze connecté', wazeOff: 'Flux Waze non connecté', wazeStale: 'Flux Waze non actualisé',
}, {
  settings: 'Language and voice', language: 'Language', voice: 'Choose voice', auto: 'Automatic voice', test: 'Test voice', humor: 'Humor', on: 'On', off: 'Off', save: 'Save', saveFailed: 'Settings not saved. Try again.',
  change: 'Change route', refresh: 'Recalculate route', alternative: 'Find another route', policy: 'Tolls', avoid: 'No tolls', allow: 'Tolls allowed', prefer: 'Based on route type', apply: 'Calculate and change', noAlternative: 'No other route found for these criteria. Keeping current route.', changed: 'New route ready.', noRoute: 'No route for these criteria. Nothing changed.',
  allowNote: 'Allowing tolls does not force a toll road. Prices unknown.', demoPin: 'You can save this place. Activate services to calculate a real route.', wazeLive: 'Waze feed connected', wazeOff: 'Waze feed not connected', wazeStale: 'Waze feed not refreshed',
});
export const favoriteLabels = localized({home:'🏠 الدار',work:'💼 الخدمة',school:'🎒 المدرسة',gym:'🏋️ لا صال',other:'⭐ بلاصة أخرى',title:'البلايص ديالي',loadFailed:'ما قدرناش نقراو البلايص. ضغط هنا نعاودو.',saveFailed:'ما تسجلاتش التغييرات. عاود جرّب.',replace:'نبدّلو هاد البلاصة؟',no:'لا',change:'بدّل',remove:'مسح',removeAsk:'نمسحو هاد البلاصة؟',hint:'اختار بلاصة بالبحث ولا ضغط مطوّل على الخريطة، ومن بعد سجّلها.',savePlace:'☆ سجّل هاد البلاصة',choosePlace:'اختار بلاصة باش تسجّلها',nameAsk:'شنو سميّة هاد البلاصة؟',name:'سميّة البلاصة',saving:'كنسجّلو…',save:'سجّل',back:'رجع'},
  {home:'🏠 Maison',work:'💼 Travail',school:'🎒 École',gym:'🏋️ Sport',other:'⭐ Autre lieu',title:'Mes lieux',loadFailed:'Lecture impossible. Touchez pour réessayer.',saveFailed:'Modifications non enregistrées. Réessayez.',replace:'Remplacer ce lieu ?',no:'Non',change:'Remplacer',remove:'Supprimer',removeAsk:'Supprimer ce lieu ?',hint:'Cherchez un lieu ou faites un appui long sur la carte, puis enregistrez-le.',savePlace:'☆ Enregistrer ce lieu',choosePlace:'Choisir un lieu à enregistrer',nameAsk:'Comment nommer ce lieu ?',name:'Nom du lieu',saving:'Enregistrement…',save:'Enregistrer',back:'Retour'},
  {home:'🏠 Home',work:'💼 Work',school:'🎒 School',gym:'🏋️ Gym',other:'⭐ Other place',title:'My places',loadFailed:'Cannot load places. Tap to retry.',saveFailed:'Changes not saved. Try again.',replace:'Replace this place?',no:'No',change:'Replace',remove:'Delete',removeAsk:'Delete this place?',hint:'Search or long press the map to choose a place, then save it.',savePlace:'☆ Save this place',choosePlace:'Choose a place to save',nameAsk:'Name this place',name:'Place name',saving:'Saving…',save:'Save',back:'Back'});
