import type { darijaUi } from './darijaAudioPrompts';
export const frUi: Record<keyof typeof darijaUi, string> = {
  brand: 'Tri9i', subtitle: 'Conduisez tranquillement, arrivez sereinement', search: 'Où allez-vous ?', find: 'Chercher',
  demo: 'Démonstration • trajet et alertes simulés', live: 'Navigation en ligne',
  locating: 'Recherche de votre position…', noGps: 'Activez la localisation et autorisez son accès.', retryGps: 'Réessayer le GPS', gpsWeak: 'Position imprécise. Patientez.',
  network: 'Connexion impossible. Vérifiez Internet et réessayez.', config: 'Les services doivent être configurés.', noResults: 'Aucun résultat. Essayez un autre nom.', calculating: 'Calcul du trajet…',
  choose: 'Choisissez votre trajet', start: 'Démarrer', stop: 'Arrêter le guidage', report: 'Signaler', sent: 'Signalement envoyé !', localSent: 'Enregistré dans cette démonstration uniquement.',
  reportFailed: 'Envoi impossible. Réessayez avec Internet.', reporting: 'Envoi…', reportUnavailable: 'Signalements indisponibles.', parked: 'À utiliser à l’arrêt ou par un passager.',
  cancel: 'Retour', close: 'OK', follow: 'Ma position', mute: 'Couper la voix', unmute: 'Activer la voix', noVoice: 'Aucune voix compatible installée. Le guidage visuel reste disponible.', voiceFallback: 'Voix arabe : la prononciation de la Darija peut être imparfaite.',
  shortestNote: 'Le plus court parmi les trajets trouvés, sans garantie de minimum absolu.', economyNote: 'Priorité sans péage, puis consommation estimée.', tollsPossible: 'Des péages restent possibles. Prix inconnu, coût minimum non garanti.', tollFree: 'Sans péage selon les données reçues',
  same: 'Même trajet que', unavailable: 'Aucun trajet avec ce critère', noTraffic: 'Trafic en direct non confirmé ici', traffic: 'Durée calculée avec le trafic disponible', alertsOffline: 'Alertes communautaires non actualisées', alertsDisabled: 'Alertes communautaires non connectées', alertsLive: 'Alertes communautaires actualisées', stale: 'Actualisation impossible : dernier trajet conservé',
  refreshed: 'Dernier calcul', minutes: 'min', km: 'km', liters: 'L estimés', mapHint: 'Appui long sur la carte pour choisir un lieu', pin: 'Lieu choisi', chooseDemo: 'Essayer à Casablanca', mapbox: 'Itinéraires et recherche : Mapbox • © OpenStreetMap',
  sourceCommunity: 'Signalement communautaire non vérifié', sourceMapbox: 'Alerte du fournisseur de trajet', sourceWaze: 'Alerte partenaire', sourceDemo: 'Alerte simulée', background: 'Gardez l’application au premier plan pour le guidage.',
};
export const enUi: Record<keyof typeof darijaUi, string> = {
  brand: 'Tri9i', subtitle: 'Drive calmly, arrive safely', search: 'Where are you going?', find: 'Search', demo: 'Demo • simulated route and alerts', live: 'Online navigation',
  locating: 'Finding your location…', noGps: 'Enable location and grant permission.', retryGps: 'Retry GPS', gpsWeak: 'Location is inaccurate. Please wait.', network: 'Cannot connect. Check Internet and try again.', config: 'Services need to be configured.', noResults: 'No results. Try another name.', calculating: 'Calculating route…',
  choose: 'Choose your route', start: 'Start', stop: 'Stop guidance', report: 'Report', sent: 'Report sent!', localSent: 'Saved in this demo only.', reportFailed: 'Could not send. Try again when online.', reporting: 'Sending…', reportUnavailable: 'Reports unavailable.', parked: 'Use while parked or ask a passenger.',
  cancel: 'Back', close: 'OK', follow: 'My location', mute: 'Mute voice', unmute: 'Enable voice', noVoice: 'No compatible voice installed. Visual guidance is available.', voiceFallback: 'Arabic voice: Darija pronunciation may be imperfect.',
  shortestNote: 'Shortest of the routes found, not a guaranteed global minimum.', economyNote: 'Toll-free first, then estimated fuel use.', tollsPossible: 'Tolls may remain. Prices unknown; cheapest toll cost not guaranteed.', tollFree: 'Toll-free according to route data', same: 'Same route as', unavailable: 'No route for this criterion',
  noTraffic: 'Live traffic unconfirmed here', traffic: 'Time calculated with available traffic data', alertsOffline: 'Community alerts not refreshed', alertsDisabled: 'Community alerts not connected', alertsLive: 'Community alerts refreshed', stale: 'Refresh failed: keeping the previous route', refreshed: 'Last calculation', minutes: 'min', km: 'km', liters: 'L estimated',
  mapHint: 'Long press the map to choose a place', pin: 'Selected place', chooseDemo: 'Try Casablanca', mapbox: 'Routes and search: Mapbox • © OpenStreetMap', sourceCommunity: 'Unverified community report', sourceMapbox: 'Route provider alert', sourceWaze: 'Partner alert', sourceDemo: 'Simulated alert', background: 'Keep the app in the foreground for guidance.',
};
